name: sherlock_benchmark
description: Benchmarks for Sherlock
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  duration: ^3.0.12
  sherlock: ^0.0.15
