name: sherlock
description: Perform efficient and customized searches on local data. Built-in autocomplete feature for search bars.
version: 0.1.4
homepage: https://github.com/antoninhrlt/sherlock
license: MIT

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  diacritic: ^0.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
